/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inua_mkulima;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author georgiegegoh
 */
public class officer1 extends javax.swing.JFrame {

    /**
     * Creates new form officer1
     */
    public officer1() {
        initComponents();JMenuBar menubar =new JMenuBar();
        JMenu post =new JMenu("POST");
        post.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent me) {
               postWindow();
            }

            @Override
            public void menuDeselected(MenuEvent me) {
                
            }

            @Override
            public void menuCanceled(MenuEvent me) {
                
            }
        });
        JMenu inbox =new JMenu("INBOX");
        //post.addActionListener((ActionListener) this);
        
     
        
        menubar.add(post);
           menubar.add(inbox);
           setJMenuBar(menubar);
           
           JToolBar toolbar =new JToolBar();
           toolbar.setFloatable(false);
           
            Container container=getContentPane();
    container.setLayout(new BoxLayout(container,BoxLayout.Y_AXIS ));
    JLabel msg=new JLabel("what are the best fertilizers??");
    container.add(msg);
    
    JButton replyBtn=new JButton("reply");
    //replyBtn.addActionListener((ActionListener) this);
    replyBtn.setToolTipText("click to reply");
    container.add(replyBtn);
    
    JLabel msg1=new JLabel("what are the best markets??");
    container.add(msg1);
   //  JTextField textfield=new JTextField("reply message");
   // container.add(textfield);
     replyBtn=new JButton("reply");
    //replyBtn.addActionListener((ActionListener) this);
    replyBtn.setToolTipText("click to reply");
    container.add(replyBtn);
           
           setSize(650,600);
           setTitle("Agricultural Officer Menu");
           setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           setLocationRelativeTo(null);
}    
public void postWindow(){
     Container container1=getContentPane();
            JLabel post=new JLabel("post");
              container1.add(post);
           JToolBar toolbar =new JToolBar();
           toolbar.setFloatable(false);
           
           //statusbar.setPreferredSize(new Dimension(-1, 22));
           //add(statusbar, BorderLayout.SOUTH);
           
           setSize(550,500);
           setTitle("POST NEW CONTENT");
           setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           setLocationRelativeTo(null);
           
             
           
        

 
}
public void actionPerformed(ActionEvent evt) {
       String replyMsg = evt.getActionCommand();
       String Msg=JOptionPane.showInputDialog(null, replyMsg);
      String[] messages = null;
      if(Msg!=null){
          messages=new String[]{Msg };
      } 
     else {
           JOptionPane.showMessageDialog(null, "please input a message reply");
    }
      System.out.println(Arrays.toString(messages));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(officer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(officer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(officer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(officer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new officer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
